# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2c441c13f1fe1a80af770846722203b8a23de03f5f1f32695b1260620f2cda103cd7a801c85d85ad889d80b47b708f26d315ce449e79847d9464e330538a11e9

test:
  secret_key_base: b3fc9e0c70e6f72197f8caab8765ae4e29937b23d4e705495e65716be717c401f3347ab3c8828bb14665915457d780ed6a7f0a9fdb15d492e07fb3d19f2200e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
